// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://limhhziszkburdweovrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbWhoemlzemtidXJkd2VvdnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzI1MDIsImV4cCI6MjA2NDkwODUwMn0.vR5luQwFLd2p9JfBI75soGOjOUz_ebsNVAUeqRLT5Xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);